name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Faz o checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura o Node.js na versão 18
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Instala as dependências
      - name: Install dependencies
        run: npm ci

      # Executa o build do projeto
      - name: Build project
        run: npm run build

      # Instala o Firebase CLI globalmente
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # Realiza o deploy para o Firebase Hosting
      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
